import { Link } from "react-router";
import { ArrowRightIcon, BrainCircuitIcon, SunIcon, MoonIcon, CheckIcon } from "lucide-react";
import { useTheme } from "../context/ThemeContext.jsx";

export function Landing() {
  const { theme, toggleTheme } = useTheme();

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-indigo-50/30 dark:from-slate-950 dark:via-slate-900 dark:to-indigo-950/20 text-slate-900 dark:text-white">

      {/* Nav */}
      <nav className="border-b border-slate-100 dark:border-slate-800 bg-white/70 dark:bg-slate-900/70 backdrop-blur-sm sticky top-0 z-10">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-600 shadow-lg shadow-indigo-500/30">
              <BrainCircuitIcon className="h-5 w-5 text-white" />
            </div>
            <span className="text-sm font-bold tracking-tight">InterviewAI</span>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={toggleTheme}
              className="flex h-9 w-9 items-center justify-center rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition shadow-sm">
              {theme === "dark" ? <SunIcon className="h-4 w-4" /> : <MoonIcon className="h-4 w-4" />}
            </button>
            <Link to="/login" className="rounded-xl px-4 py-2 text-sm font-medium text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition">
              Sign in
            </Link>
            <Link to="/register" className="rounded-xl bg-indigo-600 hover:bg-indigo-500 px-4 py-2 text-sm font-semibold text-white transition shadow-lg shadow-indigo-500/25">
              Get started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <main className="mx-auto max-w-6xl px-6 pt-20 pb-20">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 rounded-full bg-indigo-50 dark:bg-indigo-950/50 border border-indigo-100 dark:border-indigo-900 px-4 py-2 mb-8">
            <div className="h-1.5 w-1.5 rounded-full bg-indigo-500 animate-pulse" />
            <span className="text-xs font-semibold text-indigo-700 dark:text-indigo-300">Powered by Gemini AI & Groq</span>
          </div>
          <h1 className="text-5xl font-bold leading-[1.1] tracking-tight mb-6 md:text-6xl">
            Ace every interview<br />
            <span className="text-indigo-600 dark:text-indigo-400">with AI on your side</span>
          </h1>
          <p className="text-lg text-slate-500 dark:text-slate-400 leading-7 max-w-xl mx-auto mb-10">
            Upload your resume, get an AI-powered match score, practice with voice mock interviews, and track your improvement — all in one workspace.
          </p>
          <div className="flex items-center justify-center gap-3">
            <Link to="/register"
              className="inline-flex items-center gap-2 rounded-2xl bg-indigo-600 hover:bg-indigo-500 px-6 py-3.5 text-sm font-semibold text-white transition shadow-xl shadow-indigo-500/25">
              Start for free <ArrowRightIcon className="h-4 w-4" />
            </Link>
            <Link to="/login"
              className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-6 py-3.5 text-sm font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700 transition shadow-sm">
              Sign in
            </Link>
          </div>
        </div>

        {/* Feature cards */}
        <div className="grid gap-4 md:grid-cols-3 mb-10">
          {[
            { icon: "📄", title: "Resume analysis", desc: "Upload a PDF and get a job match score, skill gaps, and interview questions generated by Gemini AI.", badge: "Gemini AI" },
            { icon: "🎤", title: "Voice mock interviews", desc: "Speak your answers aloud. Groq evaluates each response in under 1 second with a score and detailed feedback.", badge: "Groq AI" },
            { icon: "📊", title: "Performance analytics", desc: "Track your scores over time, identify recurring weak areas, and see your interview readiness improve.", badge: "Dashboard" },
          ].map(f => (
            <div key={f.title} className="rounded-3xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-7 shadow-sm hover:shadow-md transition-shadow">
              <div className="text-3xl mb-5">{f.icon}</div>
              <div className="inline-block text-xs font-semibold text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-950/50 px-2.5 py-1 rounded-full mb-3">{f.badge}</div>
              <h3 className="text-base font-bold mb-2">{f.title}</h3>
              <p className="text-sm leading-6 text-slate-500 dark:text-slate-400">{f.desc}</p>
            </div>
          ))}
        </div>

        {/* What's included */}
        <div className="rounded-3xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-8 shadow-sm">
          <div className="text-xs font-bold uppercase tracking-widest text-slate-400 dark:text-slate-500 mb-5">Free plan includes</div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {[
              "20 reports per month",
              "15 resume PDF exports",
              "10 mock interview sessions",
              "Full voice AI support",
              "Analytics dashboard",
              "5-day prep plans",
            ].map(item => (
              <div key={item} className="flex items-center gap-2.5 text-sm text-slate-700 dark:text-slate-300">
                <div className="h-5 w-5 rounded-full bg-emerald-50 dark:bg-emerald-950/50 flex items-center justify-center flex-shrink-0">
                  <CheckIcon className="h-3 w-3 text-emerald-600 dark:text-emerald-400" />
                </div>
                {item}
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}